server:
  port: 9101

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Statistics

logging:
  file: logs/bi.log
  level:
    com:
      hinacom:
      bi: DEBUG
    org:
      springframework: INFO